[package]
name = "dns-enum"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = "4.4"
trust-dns-resolver = "0.23"
colored = "2.0"
tokio = { version = "1.35", features = ["full"] }

[[bin]]
name = "dns-enum"
path = "src/main.rs"